version: "3"
services:
  notey-server:
    container_name: notey-server
    build:
      context: ./server_docker
      dockerfile: Dockerfile
    volumes:
      - ./server_docker:/usr/src/server
    ports:
      - "8080:8080"
